
#连接池的配置信息
### 初始化大小，最小，最大
#spring.druid.initialSize=5
#spring.druid.minIdle=5
#spring.druid.maxActive=20
### 配置获取连接等待超时的时间
#spring.druid.maxWait=60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.druid.timeBetweenEvictionRunsMillis=60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.druid.minEvictableIdleTimeMillis=300000
#spring.druid.validationQuery=SELECT 1 FROM DUAL
#spring.druid.testWhileIdle=true
#spring.druid.testOnBorrow=false
#spring.druid.testOnReturn=false
#spring.druid.poolPreparedStatements=true
#spring.druid.maxPoolPreparedStatementPerConnectionSize=20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.druid.filters=stat,wall,log4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.druid.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 7903

hlj:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhsot:3306/yehao_test?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    username: root
    password: 123456
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat

search:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/search?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat

logging:
  config: classpath:log4j.xml
  level:
    com:
      helijia:
        storage: DEBUG


#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:sql/**.xml
#  type-aliases-package: com.helijia.storage.dao.entity