
localhost=106.13.44.20
spring:
  application:
    name: spring-boot-event-message
  redis:
    host: ${localhost}
    port: 6379
    timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

server:
  port: 8086
  address: ${localhost}

config:
  canal:
    host: ${localhost}
    port: 11111
    userName: canal
    password: canal
    batchSize: 1000

