
spring:
  application:
    name: spring-cloud-search

server:
  port: 8902


security:
  user:
    name: yehao
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8900/eureka/
  instance:
    hostname: spring-cloud-eureka-provider
